### ISSUE TITLE
When there is a QR code on the page, an error is reported

### ISSUE THREAD

**Issue by D-zy** [singpass/Singpass-app-webview-client#4]
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
        at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
        at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
        at xq.a(SourceFile:292)
        at alW.handleMessage(SourceFile:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6759)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

**Comment by kenshin171** [comment]
This is a bug with webview/chrome. The fix is in webview/chrome versions 73+. as stated here

https://bugs.chromium.org/p/chromium/issues/detail?id=925887
